### ISSUE TITLE
Mauvaise info sur l'AM avec une fatigue > 30

### ISSUE THREAD

**Issue by athimel** [Canop/Chrall#49]
Quand la fatigue dépasse 30, 1PV = 0 min.

L'aide affichée par Chrall indique des "Infinity" et "NaN"

![capture du 2015-01-08 16 43 40](https://cloud.githubusercontent.com/assets/1804382/5665105/44a6a6cc-9756-11e4-95c5-a387387c5cd4.png)

**Comment by Canop** [comment]
Merci. Est-ce qu'un kastar peut jeter un oeuil au code ?

**Comment by athimel** [comment]
Je peux ^^

À vrai dire, j'ai déjà le nez dans le code, pour une autre issue pas encore soumise

**Comment by Canop** [comment]
Bien !
Discussions plus aisées là : http://dystroy.org/miaou/167?Chrall#746331
