### ISSUE TITLE
Bug  Table "troll" - décalage de cellules

### ISSUE THREAD

**Issue by TheDudeness** [Canop/Chrall#56]
![bug affichage troll](https://cloud.githubusercontent.com/assets/13334391/8675915/8e5447e2-2a46-11e5-85f4-66e2fd2d737b.png)

**Comment by Canop** [comment]
J'ai juste pas de troll en vue pour tester ^^

**Comment by TheDudeness** [comment]
C'est reglé! Well done Canop ;)
